// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIKvXRFplOO0-Fq1LY4hngIyxPkKpgMew',
    appId: '1:112997336412:web:8dacb36bcd875ad02e6d99',
    messagingSenderId: '112997336412',
    projectId: 'livresque-app',
    authDomain: 'livresque-app.firebaseapp.com',
    storageBucket: 'livresque-app.appspot.com',
    measurementId: 'G-8ESQ0E4GK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6DFxnZ7U_kjoCmNEeBlXKqJeNrx4C8Vo',
    appId: '1:112997336412:android:96c5f02d911d67c82e6d99',
    messagingSenderId: '112997336412',
    projectId: 'livresque-app',
    storageBucket: 'livresque-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMJVbpsDLVRboZ5k1HZMRPSpOLF3XaPZ8',
    appId: '1:112997336412:ios:acf7442b869825fe2e6d99',
    messagingSenderId: '112997336412',
    projectId: 'livresque-app',
    storageBucket: 'livresque-app.appspot.com',
    iosBundleId: 'com.example.livresqueApp',
  );
}
